version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your_secret_key
      - DB_NAME=shop.db
      - JWT_SECRET=your_jwt_secret
      - MAIL_USERNAME=example@gmail.com
      - MAIL_PASSWORD=examplepassword
      - YOOKASSA_SHOP_ID=your_shop_id
      - YOOKASSA_SECRET_KEY=your_secret_key
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"